/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'erikp' at '12/26/15 11:29 PM' with Gradle 2.10
 *
 * @author erikp, @date 12/26/15 11:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
